# Generated by Django 4.2.6 on 2023-11-24 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('promotion_type', models.CharField(choices=[('No Promotion', 'NP'), ('BreakFast', 'BF'), ('Discount in Daily', 'DD'), ('Extended stay Discount', 'ED'), ('discount', 'D')], default='No Promotion')),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('discount_percentage', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
