# Generated by Django 4.2.6 on 2023-11-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='check_in_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='check_out_date',
            field=models.DateField(blank=True),
        ),
    ]
