# Generated by Django 4.2.6 on 2023-11-23 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('reserves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction'),
        ),
    ]
